export const abaBuyerKeywordSeeds = [
  "ABA practice management software",
  "ABA EMR software",
  "ABA clinic software",
  "ABA therapy software",
  "ABA scheduling software",
  "ABA billing software",
  "ABA documentation software",
  "ABA data collection software",
  "ABA session notes software",
  "ABA EHR software",
  "ABA staff scheduling software",
  "ABA caregiver communication software",
  "ABA authorization tracking software",
  "ABA utilization tracking software",
  "ABA compliance software",
  "ABA audit documentation software",
  "ABA revenue cycle management software",
  "ABA clinic operations software",
  "software for new ABA clinic",
  "ABA clinic startup software",
  "best ABA software",
  "best EMR for ABA therapy",
  "ABA EMR comparison",
  "ABA practice management system",
  "ABA therapy practice management software",
  "ABA software for startups",
  "ABA software for small clinics",
  "ABA software for new clinic",
  "ABA clinic management software",
  "ABA scheduling and billing software",
  "ABA billing and data collection software",
  "ABA data collection and scheduling software",
  "ABA session documentation software",
  "ABA authorization management software",
  "ABA insurance billing software",
  "CentralReach alternative",
  "CentralReach competitor",
  "CentralReach replacement",
  "CentralReach vs Rethink",
  "CentralReach vs Motivity",
  "CentralReach vs Catalyst",
  "Rethink Behavioral Health alternative",
  "RethinkBH alternative",
  "Motivity alternative",
  "Catalyst ABA alternative",
  "Hi Rasmus alternative",
  "ATrack alternative",
  "ABA software alternatives",
  "best CentralReach alternative",
  "best ABA EMR alternative",
  "ABA cancellation management software",
  "ABA cancelation software",
  "ABA cancelation management software",
  "ABA makeup session software",
  "ABA staff coverage software",
  "RBT callout coverage",
  "ABA cancellation recovery",
  "ABA cancelation recovery",
  "ABA recovered hours",
  "recover lost ABA hours",
  "ABA clinic lost revenue cancellations",
  "ABA clinic lost revenue cancelations",
  "ABA clinic cancellation workflow",
  "ABA clinic cancelation workflow",
  "ABA clinic makeup session workflow",
  "ABA scheduling recovery workflow",
  "ABA staff callout workflow",
  "ABA session recovery software",
  "ABA operations recovery software",
  "ABA revenue leakage cancellations",
  "ABA revenue leakage cancelations",
  "RBT support software",
  "RBT burnout solutions ABA",
  "ABA staff retention software",
  "ABA field staff support software",
  "RBT session support app",
  "RBT documentation support",
  "ABA staff communication software",
  "ABA team communication software",
  "ABA clinic staff scheduling",
  "ABA RBT scheduling software",
  "ABA RBT callout management",
  "parent communication software for ABA clinics",
  "ABA parent portal software",
  "ABA caregiver portal",
  "ABA family communication software",
  "ABA secure caregiver updates",
  "ABA parent training scheduling software",
  "ABA makeup session communication",
  "caregiver cancellation ABA software",
  "caregiver cancelation ABA software",
  "ABA session note review software",
  "ABA note review workflow",
  "ABA documentation readiness",
  "ABA clinical review software",
  "ABA proof packet",
  "ABA export packet software",
  "ABA billing documentation workflow",
  "ABA payer audit documentation",
  "ABA authorization documentation",
  "how to open an ABA clinic",
  "software for opening an ABA clinic",
  "ABA practice startup software",
  "new ABA clinic software",
  "ABA clinic operations stack",
  "ABA clinic startup checklist",
  "ABA clinic business software",
  "ABA clinic scheduling software startup",
  "ABA clinic billing software startup",
  "ABA clinic EMR startup",
  "ABA clinic owner software",
  "BCBA starting ABA clinic",
  "autism therapy software",
  "behavioral health ABA software",
  "Motivity vs Rethink",
  "how to open an ABA clinic software",
  "RBT scheduling software",
  "ABA claims billing workflow",
  "ABA credentialing software",
  "ABA clinic staff retention software"
] as const;

export const abaNegativeKeywords = [
  "jobs",
  "career",
  "salary",
  "training",
  "RBT training",
  "BCBA exam",
  "free CEU",
  "certification",
  "course",
  "school",
  "near me",
  "therapy near me",
  "autism diagnosis",
  "diagnosis",
  "Medicaid provider list",
  "parent looking for ABA",
  "ABA services for my child",
  "ABA therapy for child",
  "insurance coverage",
  "what is ABA",
  "ABA therapy near me",
  "ABA services near me",
  "child therapy",
  "school ABA jobs"
] as const;

export const best20ABABuyerKeywords = [
  "ABA practice management software",
  "ABA EMR software",
  "ABA clinic software",
  "ABA scheduling software",
  "ABA billing software",
  "ABA documentation software",
  "ABA authorization tracking software",
  "ABA caregiver communication software",
  "ABA staff scheduling software",
  "ABA compliance software",
  "CentralReach alternative",
  "RethinkBH alternative",
  "Motivity alternative",
  "Catalyst ABA alternative",
  "software for new ABA clinic",
  "ABA clinic startup software",
  "ABA cancellation management software",
  "ABA cancelation software",
  "ABA makeup session software",
  "RBT callout coverage",
  "recover lost ABA hours"
] as const;
